---
- name: Add key
  when: ssh_authorisation_uninstall == false
  block:
    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Remove key
  when: ssh_authorisation_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml
