---
- name: Remove all keys without current key
  become: true
  ansible.posix.authorized_key:
    user: "{{ authorisation_user }}"
    key: "{{ lookup('file', '{{ authorisation_current_key_file }}') }}"
    exclusive: true
    state: present
  when: authorisation_current_key_file | length > 0

- name: Remove all keys - do not use if password auth is disabled and no other user allows key auth
  become: true
  ansible.builtin.file:
    path: "/home/{{ authorisation_user }}/.ssh/authorized_keys"
    state: absent
  when: authorisation_current_key_file | length == 0

- name: Add other keys from github
  become: true
  ansible.posix.authourized_key:
    user: "{{ authorisation_user }}"
    key: "https://github.com/{{ item }}.keys"
    state: present
  loop: "{{ authorisation_github_usernames }}"

- name: Add other keys from folder
  become: true
  ansible.posix.authourized_key:
    user: "{{ authorisation_user }}"
    key: "{{ item }}"
    state: present
  with_fileglob: './keys/*.pub'
