---
- name: Add keys
  when: ssh_authorisation_uninstall == false
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml

    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Remove keys
  when: ssh_authorisation_uninstall == true
    - name: Clean
      ansible.builtin.include_tasks: clean.yml
