---
- name: Remove all keys without current key
  become: true
  ansible.posix.authorized_key:
    user: "{{ ssh_authorisation_user }}"
    key: "{{ lookup('file', '{{ ssh_authorisation_current_key_file }}') }}"
    exclusive: "{{ ssh_authorisation_exclusive | bool }}"
    state: present
  when: ssh_authorisation_current_key_file | length > 0

- name: Remove all keys - do not use if password auth is disabled or other user allows key auth
  become: true
  ansible.builtin.file:
    path: "/home/{{ ssh_authorisation_user }}/.ssh/authorized_keys"
    state: absent
  when:
    - ssh_authorisation_exclusive | bool
    - ssh_authorisation_current_key_file | length == 0

- name: Add other keys from github
  become: true
  ansible.posix.authorized_key:
    user: "{{ ssh_authorisation_user }}"
    key: "https://github.com/{{ item }}.keys"
    state: present
    comment: "# imported from github: {{ item }}"
  loop: "{{ ssh_authorisation_github_usernames }}"

- name: Add other keys from folder
  when: ssh_authorisation_local_key_path | length > 0
  become: true
  ansible.posix.authorized_key:
    user: "{{ ssh_authorisation_user }}"
    key: "{{ lookup('file', '{{ item }}') }}"
    state: present
  with_fileglob: "{{ ssh_authorisation_local_key_path }}/*.pub"
