---
- name: Add keys from github
  become: true
  ansible.posix.authorized_key:
    user: "{{ ssh_authorisation_user }}"
    key: "https://github.com/{{ item }}.keys"
    state: present
    comment: "# imported from github: {{ item }}"
  loop: "{{ ssh_authorisation_github_usernames }}"

- name: Add keys from folder
  when: ssh_authorisation_local_key_path | length > 0
  become: true
  ansible.posix.authorized_key:
    user: "{{ ssh_authorisation_user }}"
    key: "{{ lookup('file', '{{ item }}') }}"
    state: present
  with_fileglob: "{{ ssh_authorisation_local_key_path }}/*.pub"
